### ISSUE TITLE
File content disappeared

### ISSUE THREAD

**Issue by jvanheld** [rsa-tools/motif_databases#1]
A couple of years ago we switched from `git` to `git lfs` because some files exceeded github's single-file size limit (100Mb I think,  not sure anymore). 

More recently, we faced an issue when cloning the repo : 

```{bash}
git clone https://github.com/rsa-tools/motif_databases.git
Cloning into 'motif_databases'...
remote: Enumerating objects: 1272, done.
remote: Counting objects: 100% (1192/1192), done.
remote: Compressing objects: 100% (823/823), done.
remote: Total 1272 (delta 399), reused 1142 (delta 357), pack-reused 80
Receiving objects: 100% (1272/1272), 8.79 MiB | 5.46 MiB/s, done.
Resolving deltas: 100% (460/460), done.
Downloading ATtRACT/ATtRACT_2017_12.tf (790 KB)
Error downloading object: ATtRACT/ATtRACT_2017_12.tf (e1557a6): Smudge error: Error downloading ATtRACT/ATtRACT_2017_12.tf (e1557a634e2d154e21337be184f13bae5b398684c537a31372492cee9624cd49): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to /Users/jvanheld/no_backup/rsat_github/rsa-tools/test/motif_databases/.git/lfs/logs/20230208T042546.0912.log
Use `git lfs logs last` to view the log.
error: external filter 'git lfs smudge %f' failed 2
error: external filter 'git lfs smudge %f' failed
fatal: ATtRACT/ATtRACT_2017_12.tf: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

```

In fact, on github as well as on the clones or zip archives of a release, almost all the .tf files have a size of ~132 bytes, and their content (supposedly the matrix files) has been replaced by 3 lines indicating 
- the git lfs version
- a sha key (I guess this is the sha signature of the original file)
- the size of the original file

An example below

```{bash}
> cat motif_databases/JASPAR/Jaspar_2020/nonredundant/JASPAR2020_CORE_vertebrates_non-redundant_pfms.tf
version https://git-lfs.github.com/spec/v1
oid sha256:129d7523ba0c97b7fbd830502fad0c065af57d19e755662b4c322072161f30e9
size 360128
```

With the following command I can compute the sum of sizes found in all the .tf files;

```{bash}
>find . -name '*.tf' -exec grep -H '^size ' {} \; | awk -F'[: ]' 'sum += $3/1e+6 {print $3"\t"sum" Mb\t"$1}'

[...]
63988	639.424 Mb	motif_databases//REGULONDB/RegulonDB_2022_03.tf
220096	639.644 Mb	motif_databases//REGULONDB/regulonDB_2012-05.tf
529646	640.173 Mb	motif_databases//HOCOMOCO/HOCOMOCO_2017-10-17_Mouse.tf
381343	640.555 Mb	motif_databases//HOCOMOCO/HOCOMOCO_2015-08-07.tf
600394	641.155 Mb	motif_databases//HOCOMOCO/HOCOMOCO_2015-11-23_Human.tf
786522	641.942 Mb	motif_databases//HOCOMOCO/HOCOMOCO_2017-10-17_Human.tf
386310	642.328 Mb	motif_databases//HOCOMOCO/HOCOMOCO_2015-11-23_Mouse.tf
790028	643.118 Mb	motif_databases//ATtRACT/ATtRACT_2017_12.tf
218991	643.337 Mb	motif_databases//hPDI/hPDI_matrices.tf
207572	643.545 Mb	motif_databases//Aniseed/Ciona_robusta_SELEX_motifs.tf
```

The last line shows the total size that should be expected in this repo : 643.5 Mb. However the repo only weights 47Mb. 

Does anyone know how to recover the real content of these files ?

I found a discussion here with some solutions, but they seem a bit tricky and dangerous. 
- <https://github.com/nabla-c0d3/nassl/issues/17>

**Comment by eead-csic-compbio** [comment]
Hi @jvanheld , have you checked the size of the motif files compressed?

**Comment by jvanheld** [comment]
Morgane just provided us with a version from March 2nd, 2022.

The compressed archive weights 257Mb. 

The uncompressed folder makes 1271Mb, which includes 636Mb for the .git folder (the data is thus ~half of the content, and the git history the other half).

**Comment by brunocontrerasmoreira** [comment]
I can confirm that the file contents are back, the repo seems to be working again as expected
